### PR TITLE
Create security urgently

### PR DESCRIPTION
**Pull request by KaAwatea**
Version 6.x.x supported current LTS but 2 opened yet over 1,000 closed.

Urgent security to be ACTIONED as soon as possible.  Before Friday end of September 2022.

Vergecurrency illegitimate. 🌡️🪫🖲️⛑️

To be reviewed as stated above

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by KaAwatea** [comment]
To be ACTIONED asap

**Review by KaAwatea — COMMENTED** [review]
KaAwatea:patch-1
ethereum-daily-transacti

**Comment by justinvforvendetta** [comment]
what do you mean? 

7.x supports 18.04 and 22.04

**Comment by KaAwatea** [comment]
All done

**Pull request closed without merging**
