### PR TITLE
Fixing how DNS seeds are declared

### PR DESCRIPTION
**Pull request by corymsmith**
This fixes the DNS seeds so all 10 are used, previously 5 of them were unused and acted as the source.

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
@corymsmith actually we're about to remove all these, and use .onion seeds (we're working on this in the tor_integration branch)

**Comment by corymsmith** [comment]
@justinvforvendetta I was actually wondering about that after chatting with @ekryski yesterday but figured I'd submit anyways.

**Comment by justinvforvendetta** [comment]
thanks @corymsmith if you want to take a peek at the tor_integration branch be our guest =]

**Comment by mnott** [comment]
@somid3 thanks for the reference to Principles on the other thread - (and also for the very good tone of discussion) - I'll have hence something to read while waiting for the rebound...

@justinvforvendetta I'd be great not to see these topics locked, and be less expulsive on people who just need to steam off. Maybe he's really in a problem because of his investment, and hence we should show compassion. Yes, his tone was not appropriate, but then otoh, who hasn't had a bad day. Just suggesting. Me following these discussions, while also quite down on the investment as of now, at least gave me some good read for the night.

**Pull request closed without merging**
