### PR TITLE
Tor Hidden Services v3

### PR DESCRIPTION
**Pull request by marpme**

### CODE REVIEW

**Comment by marpme** [comment]
image

**Comment by karanpatel863** [comment]
So is it safe to say that new TOR v3 nodes will be live soon?

**Comment by karanpatel863** [comment]
-Remove my laziness
Hmm will add it to my to-do list 😅

**Comment by marpme** [comment]
Well @karanpatel863, once 5.0.0 is released we will by default start v3 hidden services since they are more secure to most network based attacks.

**Comment by justinvforvendetta** [comment]
@karanpatel863 there are some v3 nodes up already but this commit allows them from within

**Comment by justinvforvendetta** [comment]
also I'll be pushing the patch to remove rust shortly

**Comment by karanpatel863** [comment]
Awesome. Will wait for 5.0 to try TOR v3 default nodes by myself.

**Comment by karanpatel863** [comment]
In the meantime justin and marpme please have a look at dandelion++
researched by giulia fanti & team. Dandelion++ is a lightweight and
straightforward network layer solution with formally guaranteed anonymity
that can easily be implemented with existing cryptocurrencies.
Currently it is being considered to be added via BIP along with taproot in
bitcoin.
I am attaching arxiv research papers containing dandelion and then updated
dandelion++. Kindly have a look & you will find it interesting.

**Comment by karanpatel863** [comment]
[1701.04439(1).PDF](https://github.com/vergecurrency/VERGE/files/2873059/1701.04439.1.PDF)
[1805.11060.pdf](https://github.com/vergecurrency/VERGE/files/2873060/1805.11060.pdf)

**Pull request merged**
