### PR TITLE
Update go.sh

### PR DESCRIPTION
**Pull request by malt0se**
Option for building static berkeley libs

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
hmm, maybe we can make a release flag for the bash script, so the option can just be passed thru command line? static would be required for a release or portable binary.. nice work =]

**Comment by marpme** [comment]
We could also try to using an “higher” language (i.e. NodeJS), if those are easier to handle instead of Shell. Just hint because I see like 372 patches :p - _just throwing that into the room!_

Still very well done, thank you 😊

**Comment by malt0se** [comment]
@marpme 
No, thank you!
What a fascinating idea!. Why don't you use NodeJS for counting patches?

**Comment by Positivism** [comment]
Marpme loves his node&realscript, can't balme him 😂

**Comment by malt0se** [comment]
Sure. Meant no offence :-)

**Comment by marpme** [comment]
Everything alright just trying to give some useful hints tho :)

**Pull request merged**
