### PR TITLE
fixing syncing of pos blocks

### PR DESCRIPTION
**Pull request by EclipseCrypto**

### CODE REVIEW

**Comment by vergecurrency** [comment]
yeah this coin is strictly PoW, but was built from a PoW/PoS coin. i'll look into this now.

**Comment by EclipseCrypto** [comment]
If there are no PoS blocks, this won't help.

For some reason you are not getting a blocks from the CNode here then

https://github.com/EclipseCrypto/VERGE/blob/18ccb47f55c7a359ba8202142720f4f12a44cc20/src/main.cpp#L2335

**Comment by vergecurrency** [comment]
@EclipseCrypto we have had 300gh/s scrypt hash coming onto our network, while it is as 10gh/s and driving the difficulty up, and they are spv mining, so i think that is why we're seeing that issue.

**Comment by EclipseCrypto** [comment]
Talk to bittrex-richie but he claims to be behind on blocks compared to an explorer. It's not related to diff from what he says.

**Pull request closed without merging**
