### PR TITLE
Update multi-algo template composition

### PR DESCRIPTION
**Pull request by marpme**
Opens for miners the possibility to choose what algorithm is currently being interesting and they need a template for. With this change, you now can pass a parameter called `algo` into the common request structure to retrieve a block specifically for this algorithm.

Moreover, it is saving them a lot of resources and thus money as they don't have to host 5 different verge nodes.

### CODE REVIEW

**Comment by Positivism** [comment]
Can we mine multiple algorithms at the same time? That functionality would be useful.

**Comment by justinvforvendetta** [comment]
@Positivism not unless you are allocating your hardware for diff algos and running multiple mining software instances

**Comment by Positivism** [comment]
@justinvforvendetta That's what I figured, we'll just have to have multiple VERGEd instances when working with multiple algorithms if you mine more than one or own a pool that has more than one algorithm. If I'm understanding @marpme's comment correctly, it isn't very useful to be able to switch algorithms one at a time and doesn't save much resources or money, increasing the block reward would do a much better job of doing that, there's an asymptotic relation between price and difficulty for XVG, because there are enough people who mine verge regardless of price it actually hurts miners in the long run and discourages mining it in general.

**Comment by marpme** [comment]
Well that commit should exactly establish you to do exactly this. You’ll be able to create all blocktemplate on one core node. You can now just pass an algorithm parameter which will be respected for the upcoming template. 

That way you should be able to run one node and still mine all the algorithms.

**Comment by pinpins** [comment]
We would need also changes in getblock, adding algorithm block was found with. 
This is needed to proper reward distribution. 


`

getblock 437363cb9333f825baf8883adcbad9531598d27b1287cbfa3c8bec85f255f8a5
 
{
    "hash": "437363cb9333f825baf8883adcbad9531598d27b1287cbfa3c8bec85f255f8a5",
    "confirmations": 9,
    "strippedsize": 263,
    "size": 263,
    "weight": 1052,
    "height": 818528,
    "algo": "blake2s",
    "algoid": 16,
    "algopowhash": "000000000000009cc1a197b3a7b30919f40d6a3a9da64428f8cc489718ea7e07",
    "version": 540811776,
    "versionHex": "203c2200",
    "merkleroot": "80624607512bf818c271311ce66e05ccf24c5d2bb3ce628386a4322d45e9a335",
    "tx": [
        "80624607512bf818c271311ce66e05ccf24c5d2bb3ce628386a4322d45e9a335"
    ],
    "time": "2019-09-02 08:12:55 +0300",
    "mediantime": "2019-09-02 08:07:28 +0300",
    "nonce": 3375203481,
    "bits": "1a049343",
    "difficulty": 3666901.8471667,
    "chainwork": "00000000000000000000000000000000000000000000015bdbd0ac56295e16cc",
    "previousblockhash": "277f5485ee5357f22c284c50b3ab5bf7d0f510416dcc521fd0d386ab037377c2",
    "previousalgohash": "685719b51736f4f450c451638f9ddb343277125edf6358033a21843d3e23973a",
    "nextblockhash": "1b7e5dea3cb44e341b711773bbcce4cf502b1bdcab569e90c6da81cda3d0f74e"
}`

**Comment by marpme** [comment]
@pinpins the block already has a field saying `”algo”: “blake2s”`
Isn’t that what you requiring here?

**Comment by pinpins** [comment]
oh, yes it does, indeed, sorry I was under impression I checked some time ago and it was not there :)

**Pull request merged**
