### PR TITLE
Included Translation

### PR DESCRIPTION
**Pull request by nonspa**
Included the translations

### CODE REVIEW

**Comment by CHUPAfromRO** [comment]
Can you please include romanian/moldavian translation from my pull request? I don't know what i've done wrong since is my first time on github.

**Comment by jrsikors** [comment]
I created a new/latest src/qt/bitcoin_locale.qrc on pull req #654

**Comment by jrsikors** [comment]
correction, #655

**Comment by jrsikors** [comment]
closing , #659 took care of all updates.  Thanks though @nonspa

**Pull request closed without merging**
