### PR TITLE
Updated Dutch Language

### PR DESCRIPTION
**Pull request by juultje123**
Updated Dutch Language, since there were some blank translations and minor grammar mistakes.

### CODE REVIEW

**Comment by paradoxicalNL** [comment]
Hmm had de entries ook al gedaan, mijne alleen niet door de travis test. Ik kan niet vinden waarom, enig idee?

Soz for dutch :)

**Comment by JazSingh** [comment]
@paradoxicalNL That is because Travis builds timeout sometimes

**Comment by paradoxicalNL** [comment]
That must be reason then. Thanks for clarifying

Op 5 jan. 2018 6:13 p.m. schreef "Jaspreet Singh" <notifications@github.com

**Comment by juultje123** [comment]
Sorry, see if there is something missing still. Some existing translations were out-of-the-box Google translate. Lot of work though :P

**Comment by paradoxicalNL** [comment]
I will take another look once this is merged!

**Comment by jrsikors** [comment]
Just FYI - we have 3 different pull requests for Dutch translation:
#384  - @juultje123 
#363  - @paradoxicalNL
#329  - @juultje123

**Comment by jrsikors** [comment]
closing, dutch language file brought in

**Pull request closed without merging**
