### PR TITLE
4.0 release beta wraith protocol

### PR DESCRIPTION
**Pull request by justinforvendetta**
merging updated wraith branch

### CODE REVIEW

**Comment by ndnorris** [comment]
Dude seriously. Get a fucking life.

**Comment by fr4z3n** [comment]
Delete this trash!

**Comment by omicr0n** [comment]
# Fake pull is fake.... 

Not the real justin **_V_** for vendetta

**Comment by AliUz** [comment]
Seriously, this is a huge disrespect to the developer. If you support this project or not, stop messing with the codebase and stop opening useless PRs. What a disgrace.

**Comment by AceTech07** [comment]
The community is on the fake news asap though.  Good shit

**Pull request closed without merging**
