### PR TITLE
fix https://github.com/vergecurrency/VERGE/issues/211

### PR DESCRIPTION
**Pull request by jlaureano**
Fix for https://github.com/vergecurrency/VERGE/issues/211

Added qt/res/icons/address-book_filled.png to bitcoin.qrc and Makefile.qt.include

Fix for https://github.com/vergecurrency/VERGE/issues/281

Took https://github.com/vergecurrency/verge-graphics/blob/master/Wallet%20Icons/verge.icns and updated project verge.icns

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
yeah was literally making those changes, heheh

**Comment by justinvforvendetta** [comment]
@jlaureano not sure why this failed, looked solid

**Comment by justinvforvendetta** [comment]
@jlaureano the frikken file name had a space hiding in it! 

src/qt/res/icons/address-book_filled .png → src/qt/res/icons/address-book_filled.png

🙄

**Comment by jlaureano** [comment]
@justinvforvendetta I saw that and changed it in my local clone, it showed a delete for the file with the space and an add for the renamed file. Probably did not add it. Anyways, good catch! Anything I can do to help hit me on Twitter @ joselaureano

**Pull request merged**
