### PR TITLE
Enable core tests

### PR DESCRIPTION
**Pull request by Max-Meldrum**
## Description

Updates makefiles so that tests in src/test can be executed. A majority of the unit tests are functional, some needs to be updated, left commented in Maketest.test.include for now.

Some flag options are commented out instead of deleted. Thought they perhaps could be discussed etc..

## How Has This Been Tested?
Openssl 1.0.2g
Boost 1.58.0
Ubuntu 16.04

Has not been tested on Win/OS X.

## Screenshots (if appropriate):

test_verge

## Checklist:

- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Max-Meldrum** [comment]
Travis having problems with:

Assertion failed: (block.GetHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)), function LoadBlockIndex, file main.cpp, line 2902

**Comment by justinvforvendetta** [comment]
hmm travis is quite the fickle one.

**Comment by justinvforvendetta** [comment]
i restarted travis, should make it thru the linux build if it passed mac. sometimes travis times out, and also, we're using xenial as the os, and i know github has still been working on full xenial support. we kind of jumped the gun on moving from trusty to xenial.

**Comment by justinvforvendetta** [comment]
need to test this without the conflicts

**Comment by Max-Meldrum** [comment]
@justinvforvendetta conflicts fixed

**Pull request merged**
