### PR TITLE
New wraith fully implementation

### PR DESCRIPTION
**Pull request by vergecontrib**
Wraith protocol full implentation. Release date ontrack to the 30th.

### CODE REVIEW

**Comment by berkarslan-cs** [comment]
Is this legit??

**Comment by srugea** [comment]
- copy-pasta random TOR code, also why are FPU operations implemented in ASM here?
- dev has only college laboratories projects
-> ~anti-FUD FUD for value increase

**Comment by HomeY** [comment]
The fact that the team mentioned that they won't announce a date, and the account that did the pull request is only 3 hours old.... do the math :)

**Comment by michaeltieso** [comment]
It's fake.

**Comment by fskandrani** [comment]
@michaeltieso source?

**Comment by pinguluk** [comment]
Lmao nice pump attempt

**Comment by justinvforvendetta** [comment]
definitely fake.

**Comment by kiennd** [comment]
:)).

**Comment by Jabarda** [comment]
at least he tried ^_^

**Comment by Chillyo** [comment]
@justinvforvendetta I have faith that you won't ruin everyone's start to 2018 :)  The fact you are even responding to this nonsense shows you are still actively working/monitoring github which is a very positive sign.

**Comment by jhanink** [comment]
haha, the verge coin world is the craziest I've seen. seriously. I've never seen as much hype, as much fud, fake news, panic, hacked twitters... truly amazing times!

**Pull request closed without merging**
