### PR TITLE
Fix linux build errors

### PR DESCRIPTION
**Pull request by yentangen**
Notes:

1. Removed radio.png and chat.png references from project since it doesn't appear to be used anymore (See issue [138](https://github.com/vergecurrency/VERGE/issues/138) and commit [efa30d9]( https://github.com/vergecurrency/VERGE/commit/efa30d90f24b293d2b6f2eb7f48fcad78dd2c52a))
2. Commented out CWallet::Lock() prototype from wallet.h since there is no implementation and the parent class already has an implementation (unless there are plans to override this method...)
3. Some small file checking and directory creation check in go.sh to prevent some errors that may be misleading.

### CODE REVIEW

**Comment by yentangen** [comment]
Looks like I accidentally fixed the Windows build too..! Happy days.

**Comment by JBetser** [comment]
I think removing those png breaks the build:
make[1]: *** No rule to make target `qt/res/icons/chat.png', needed by `qt/qrc_bitcoin.cpp'.  Stop.

**Comment by yentangen** [comment]
@JBetser  I was able to build it locally on my ubuntu 16 VM before pushing to remote. Also, the travis build was successful as you can see in this thread. 

Based on the commit link in my description I assumed that these two png are not to be used again and can therefore be removed. 

If it's failing when you build it then please post your execution logs here.

**Comment by thomasmodeneis** [comment]
Thats correct, I just ran the build with master and ran into:

```
  CXX      qt/qt_libbitcoinqt_a-moc_qrcodedialog.o
  GEN      qt/moc_walletmodel.cpp
  CXX      qt/qt_libbitcoinqt_a-moc_walletmodel.o
make[1]: *** No rule to make target 'qt/res/icons/chat.png', needed by 'qt/qrc_bitcoin.cpp'.  Stop.
make[1]: Leaving directory '/opt/crypto/verge/vergecurrency/VERGE/src'
Makefile:524: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

So I tested the branch with fixes and all builds fine:
```
make[2]: Leaving directory '/opt/crypto/verge/vergecurrency/VERGE/src/leveldb'
  CXXLD    VERGEd
  CXX      qt/qt_VERGE_qt-bitcoin.o
  OBJCXXLD qt/VERGE-qt
make[1]: Leaving directory '/opt/crypto/verge/vergecurrency/VERGE/src'
make[1]: Entering directory '/opt/crypto/verge/vergecurrency/VERGE'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/opt/crypto/verge/vergecurrency/VERGE'
```

**Comment by mikeuding** [comment]
@thomasmodeneis , i also confirm

**Comment by JBetser** [comment]
ok I originally was compiling without your change, thinking I had the latest, looks good

**Comment by justinvforvendetta** [comment]
I'll approve this merge when I get home in the morning. cheers!

**Pull request merged**
