### PR TITLE
update src/qt/bitcoin_locale.qrc and makefile.qt.include for new translations

### PR DESCRIPTION
**Pull request by jrsikors**
per https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md

adding all the latest translations

https://www.loc.gov/standards/iso639-2/php/code_list.php

Went through the new pull requests and the existing translation files and organized / updated bitcoin_locale.qrc with the latest as of 3/25/2018 .. I think :smile:

### CODE REVIEW

**Comment by jrsikors** [comment]
Compiles Windows OK, but errors out for Mac and UNIX.   

Potential reasons because many of the files I'm including aren't technically merged yet and don't exist?

**Comment by jrsikors** [comment]
Mac error:

> Undefined symbols for architecture x86_64:
>   "qInitResources_bitcoin_locale()", referenced from:
>       _main in qt_VERGE_qt-bitcoin.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [qt/VERGE-qt] Error 1
> make[1]: *** [check] Error 2
> make: *** [check-recursive] Error 1
> cat: src/test-suite.log: No such file or directory
> The command "./building/${VERGE_PLATFORM}/build.sh" failed and exited with 1 during .
> 



Linux error:

> E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
> E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
> E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
> E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
> E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
> E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
> The command "./building/${VERGE_PLATFORM}/requirements.sh" failed and exited with 100 during

**Comment by jrsikors** [comment]
I'm pretty sure that once pulls: #420 , #311 , #359 , #319 , #303 , #367  , #313 are merged , this will compile fine ?

These 2 files contain updates for the new translations in the pulls above, and a fix for the polish one missing from bitcoin_locale.qrc

Comments / advice appreciated !

**Comment by Max-Meldrum** [comment]
yes, the bitcoin_x.ts files needs to be there, hence the crashing

**Comment by jrsikors** [comment]
and since I can't push the ts files there, only verge devs can , this will just need to be merged "last".

After those other ones are merged... this can be merged and should work ok!

Thanks for reviewing @Max-Meldrum  !

**Comment by jrsikors** [comment]
and I know it's probably not good practice to do it this way - but I didn't want to go take all the new .ts files from other peoples repo's into mine and then create 1 big pull request... but if you think that's a better way to do it .. i will gladly.  I just feel dirty like I'm stealing credit :smile:

**Comment by jrsikors** [comment]
So i went and downloaded all the TS files from all the different repos.  I got 2 options
  Option A)  Remove this pull request.  Add all their TS files to MY Repo.  Create new pull request
  Option B)  Leave it as is -- and just try to work with the devs to make sure they do this one last

If I go the option A route -- it would essentially nullify the 'contribution' from the others?  I couldn't figure out how to really do a pull from their repo into my repo.  I could only figure out how to download the different TS files.

I guess in theory -- the devs could still merge all their requests.  

The only reason I would be doing this is to try to get it to compile properly on this pull request.  I won't be able to get this to compile because the TS files are missing from the verge master repo.  They are sitting here as pull reqs, just not merged to master yet.

I don't know, someone tell me what to do :smile:

**Comment by jrsikors** [comment]
updating chart/status of pull reqs and translations

file | language | pull req | in master | bitcoin_locale.qrc | makeflile.qt.inc | merged
-- | -- | -- | -- | -- | -- | --
bitcoin_en.ts | english |   | x | x | x |  
bitcoin_es.ts | spanish | 334 | x | x | x |  
bitcoin_fr.ts | french | 333 | x | x | x |  
bitcoin_nb.ts | Norwegian |   | x | x | x |  
bitcoin_nl.ts | dutch | 384,363, 329,332 | x | x | x |  
bitcoin_ru.ts | russian |   | x | x | x |  
bitcoin_tr.ts | turkish | 331, 320 | x | x | x | 3/26/2018**
bitcoin_pl.ts | polish |   | x |   |   |  
bitcoin_cn.ts | chinese | 420 | x |   |   | 3/26/2018
bitcoin_de.ts | german | 311 | x |   |   | 3/26/2018
bitcoin_el.ts | greek | 359 |   |   |   |  
bitcoin_it.ts | italian | 319 | x |   |   | 3/26/2018
bitcoin_ptbr.ts | brazilian   portuguese | 303 |   |   |   |  
bitcoin_ro.ts | romanian/moldavian | 367 |   |   |   |  
bitcoin_ua.ts | ukranian | 313 |   |   |   |

**Comment by jrsikors** [comment]
closing -- found a couple issues -- will make pull request with better version

**Pull request closed without merging**
