### PR TITLE
update linux build instruction, make clean

### PR DESCRIPTION
**Pull request by topcatx**
Updating linux build doc  https://github.com/vergecurrency/VERGE/blob/master/building/linux/requirements.sh#L9
(seems we need libcap-dev)

Also, adding make clean before make just so any previous remains are cleaned up.

### CODE REVIEW

**Comment by CryptoRekt** [comment]
@justinvforvendetta Check this.

**Comment by justinvforvendetta** [comment]
@topcatx why make clean after autoconf, but before making? just to make sure theres no old build files around?

**Comment by justinvforvendetta** [comment]
@topcatx why make clean after autoconf, but before making? just to make sure theres no old build files around?

**Comment by topcatx** [comment]
@justinvforvendetta yep.

**Comment by justinvforvendetta** [comment]
@topcatx yeah thats what i figured. thanks for the pr =]

i must have been exhausted when i put libncap instead of libcap lol glad you caught it

**Pull request merged**
