### PR TITLE
fixing translation engine

### PR DESCRIPTION
**Pull request by stefanoferi**
Hi @justinvforvendetta 
to make the multilingual work properly:
- I created a bitcoin_locale.qrc file dedicated for translations (note inside that the file extension must be .qm not .ts) 
- I adjusted Makefile.qt.include and bitcoin.cpp accordingly
- I have also fixed some bugs in es and nl files to make compiling succeed

I point out that the base file bitcoin_en.ts is not correct because it is not updated with the latest changes made to the application, so not even all the translation files are correct.

Cheers
Stefano

### CODE REVIEW

**Comment by wertzuiop123** [comment]
Hi, 

->I have also fixed some bugs in es and nl files to make compiling succeed

could you please check DE too? Finished it today

**Comment by jrsikors** [comment]
correction, #655

**Comment by jrsikors** [comment]
hey @stefanoferi  .. quick question as well.. about your pull

In this file you edited:
src/Makefile.qt.include

You added:
`+QT_QRC_LOCALE_CPP = qt/qrc_bitcoin_locale.cpp`

I don't see a qt/qrc_bitcoin_locale.cpp .  I'm not sure if it matters or not.  I'm not an expert coder so if you say it's right, then I will not argue :smile:

**Comment by jrsikors** [comment]
@stefanoferi I would also love your thoughts on my pull req #655  , which updates a couple of these files.

It won't compile -- but I think if/when Justin merges all the .ts files it will compile fine right?

**Pull request merged**
