### PR TITLE
[FEATURE] Upgrading the language standard to CXX14

### PR DESCRIPTION
**Pull request by marpme**
G++ 4.6+ as compiler is needed

## Description / Motivation and Context
The motivation behind this change is to upgrade this project to a new level
as most of the older language features are still compliant with newer compilers.

I hope that there aren't any other unforeseen issues by setting up such a 
requirement. If so please let me know, so that we can find a solution for those.

## How Has This Been Tested?
Functional testing (a bit clicking around, some core functionalities)

## Screenshots (if appropriate):
finally fresh language features! :heart: 

image

```cpp
auto mi = mapBlockIndex.find(hash);
if (mi != mapBlockIndex.end())
    return (*mi).second;
```

## Types of changes

- [x] Breaking change (fix or feature that **MAY** cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by marpme** [comment]
Windows seems to have problems on the CI, I‘ll have a look into it tomorrow.

**Comment by jrsikors** [comment]
Mac keeps erroring out .. dont know if it's a Travis thing or not.  Trying once more

```
5 warnings generated.
  CXX      libbitcoin_server_a-keystore.o
  CXX      libbitcoin_server_a-main.o
main.cpp:1980:34: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
            printf("Postponing %"PRIszu" reconnects\n", vpindexSecondary.size());
                                 ^
                                  
main.cpp:4000:43: warning: format specifies type 'unsigned int' but the argument has type 'size_type' (aka 'unsigned long') [-Wformat]
    printf("ProcessMessages(%u bytes)\n", vRecv.size());
                            ~~            ^~~~~~~~~~~~
                            %lu
1 warning and 1 error generated.
make[2]: *** [libbitcoin_server_a-main.o] Error 1
make[1]: *** [check] Error 2
make: *** [check-recursive] Error 1
cat: src/test-suite.log: No such file or directory
The command "./building/${VERGE_PLATFORM}/build.sh" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by jrsikors** [comment]
probably Travis, build 1068 giving same error from latest commit
https://travis-ci.org/vergecurrency/VERGE/builds/367336721

**Comment by marpme** [comment]
@jrsikors As far I had a look into the mac build, it seems like that the compiler is running in some sort of strict mode. As the other ones pointed this thing out as warning, but not as an error.

**Comment by marpme** [comment]
Can be closed @michpiatek has raised the language requirement already :+1: 

Commit: 254ec379359c8302a0cb46c6b6bc7b3c6d00529e 
- Fix "No working boost sleep implementation" error.

**Pull request closed without merging**
