### PR TITLE
Fix the ALGO bit mask

### PR DESCRIPTION
**Pull request by pallas1**
Requires hardfork, fixes blake and x17 block checks.

### CODE REVIEW

**Comment by vergecurrency** [comment]
ok make the fork for block 350,000 and i will merge this later today along with some other updates, and release wallets tomorrow.

**Comment by pallas1** [comment]
added the height check, let me know if it looks good to you ;-)

**Comment by vergecurrency** [comment]
wouldnt that use the new algo, and switch it to ALGO_BROKEN which has the same value as now at that height? or am i looking at it backwards

**Comment by pallas1** [comment]
It will use "broken" until 349999

**Comment by pallas1** [comment]
So is it OK? I've tested it myself but what about you, any doubts left?

**Comment by vergecurrency** [comment]
@pallas1 yes it looks good, im just tryin to get the rest of the updates done and decide whether we stick with 350k or i bump it to 355k.. i just need to finish the getdifficulty and networkhash commands

**Comment by pallas1** [comment]
I have a fix for the difficulty reporting. It also allows solo and wallet mining. Will post asap.

**Comment by vergecurrency** [comment]
i added an rpc return for each algo's difficulty, so half of it is done, and commited. ill keep an eye on the repo =]   thanks for contributing.

**Comment by pallas1** [comment]
I've created the other pull request just now :-)

**Comment by vergecurrency** [comment]
modified to fork at 380,000
thanks!

**Pull request closed without merging**
