### PR TITLE
update text : 25 block confirmation to 140

### PR DESCRIPTION
**Pull request by jrsikors**
fix for #774

### CODE REVIEW

**Comment by Positivism** [comment]
Just curious why did we make this 140?

**Comment by justinvforvendetta** [comment]
it was always 140, for newly min(t)ed coins

**Comment by Positivism** [comment]
Right, but why 140 instead of a lower number?

**Comment by Positivism** [comment]
140 because fruit.

**Comment by justinvforvendetta** [comment]
frugivores

**Comment by Positivism** [comment]
Wouldn't frugivores be satisfied by (acceptBlockPerAlgo+1)^2 or something? i.e. 36 fruits instead of 140 fruits?

**Comment by justinvforvendetta** [comment]
well the longer newly minted coins take to be mature, the better. it's always been 140, which isn't really long anyway.. an hour and change..

**Comment by Positivism** [comment]
2crycq

**Pull request merged**
