### PR TITLE
fix for fee issue

### PR DESCRIPTION
**Pull request by michpiatek**

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
this has been a fun night eh?
[](http://image.boomsbeat.com/data/images/full/53773/tumblr_m8tjhpmned1rvk0h5o1_500-gif.gif)
image

**Comment by bonchien** [comment]
Awesome glad you are keeping spirits up!

**Comment by CChristopherNguyen2012** [comment]
Dang you guys are awesome with your work, a lot of dedication. I really don’t care if it’s done today or not I just love your work.

Sent from Mail for Windows 10

**Comment by sasasavic82** [comment]
lol mint... my holiday has been spent glued to twitter, CoinSpot and this repo... missus is super pissed lol.

My holidays end this week, i shall start contributing to the repo. @sunerok let me know how I can contribute outside of the core engine as well... i specalize in distributed systems design, microservices and building highly available infrastructure.... also AI/ML through my research... https://www.linkedin.com/in/sasasavic/

Let me know how I can help

**Comment by princealit** [comment]
You should care if it’s done.

**Comment by ccharrison** [comment]
Are we still on track for a release before midnight?

**Comment by thomasmodeneis** [comment]
Is this the fee issue that was breaking the build ?
```
wallet.cpp: In member function ‘bool CWallet::CreateTransaction(const std::vector<std::pair<CScript, long long int> >&, CWalletTx&, CReserveKey&, int64&, int32_t&, const CCoinControl*)’:
wallet.cpp:1487:17: error: ‘class CTxOut’ has no member named ‘IsDust’; did you mean ‘IsNull’?
       if (txout.IsDust(MIN_RELAY_TX_FEE))
                 ^~~~~~
                 IsNull
wallet.cpp:1489:8: error: ‘strFailReason’ was not declared in this scope
        strFailReason = _("Transaction amount too small");
        ^~~~~~~~~~~~~
wallet.cpp:1474:12: warning: unused variable ‘nFee’ [-Wunused-variable]
    int64_t nFee = 0.01*COIN;
            ^~~~
wallet.cpp: In member function ‘bool CWallet::CreateTransaction(CScript, int64_t, std::__cxx11::string&, CWalletTx&, CReserveKey&, int64&, const CCoinControl*)’:
wallet.cpp:1620:109: error: no matching function for call to ‘CWallet::CreateTransaction(std::vector<std::pair<CScript, long long int> >&, CWalletTx&, CReserveKey&, int64&, int&, std::__cxx11::string&, const CCoinControl*&)’
     bool rv = CreateTransaction(vecSend, wtxNew, reservekey, nFeeRet, nChangePos, strFailReason, coinControl);
                                                                                                             ^
wallet.cpp:1453:6: note: candidate: bool CWallet::CreateTransaction(const std::vector<std::pair<CScript, long long int> >&, CWalletTx&, CReserveKey&, int64&, int32_t&, const CCoinControl*)
 bool CWallet::CreateTransaction(const vector<pair<CScript, int64> >& vecSend, CWalletTx& wtxNew, CReserveKey& reservekey, int64& nFeeRet, int32_t& nChangePos, const CCoinControl* coinControl)
      ^~~~~~~
wallet.cpp:1453:6: note:   candidate expects 6 arguments, 7 provided
wallet.cpp:1596:6: note: candidate: bool CWallet::CreateTransaction(CScript, int64_t, std::__cxx11::string&, CWalletTx&, CReserveKey&, int64&, const CCoinControl*)
 bool CWallet::CreateTransaction(CScript scriptPubKey, int64_t nValue, std::string& sNarr, CWalletTx& wtxNew, CReserveKey& reservekey, int64& nFeeRet, const CCoinControl* coinControl)
      ^~~~~~~
wallet.cpp:1596:6: note:   no known conversion for argument 1 from ‘std::vector<std::pair<CScript, long long int> >’ to ‘CScript’
Makefile:2740: recipe for target 'libbitcoin_wallet_a-wallet.o' failed
make[1]: *** [libbitcoin_wallet_a-wallet.o] Error 1
make[1]: Leaving directory '/opt/crypto/verge/vergecurrency/VERGE/src'
Makefile:524: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

I pulled from master and it builds: 

```
  CXX      qt/qt_libbitcoinqt_a-overviewpage.o
  CXX      qt/qt_libbitcoinqt_a-sendcoinsentry.o
  CXX      qt/qt_libbitcoinqt_a-signverifymessagedialog.o
  CXX      qt/qt_libbitcoinqt_a-transactiondesc.o
  CXX      qt/qt_libbitcoinqt_a-transactionrecord.o
  CXX      qt/qt_libbitcoinqt_a-transactiontablemodel.o
  CXX      qt/qt_libbitcoinqt_a-walletmodel.o
  CXX      qt/qt_libbitcoinqt_a-moc_blockbrowser.o
  GEN      qt/qrc_bitcoin.cpp
  CXX      qt/qt_libbitcoinqt_a-qrc_bitcoin.o
  AR       qt/libbitcoinqt.a
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      VERGEd-daemon.o
  CXXLD    VERGEd
  CXX      qt/qt_VERGE_qt-bitcoin.o
  OBJCXXLD qt/VERGE-qt
make[1]: Leaving directory '/opt/crypto/verge/vergecurrency/VERGE/src'
make[1]: Entering directory '/opt/crypto/verge/vergecurrency/VERGE'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/opt/crypto/verge/vergecurrency/VERGE'
```

**Comment by justinvforvendetta** [comment]
yeah it was. we had alot of fun fixing it lol

**Pull request merged**
