### PR TITLE
Do-not-merge-testing-CI

### PR DESCRIPTION
**Pull request by BobbyMcWho**

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
@BobbyMcWho configure: error: libdb_cxx headers missing

OSX Y U HATE DB4.8?!

**Comment by lycanlee** [comment]
seems to be common error https://github.com/bitcoin/bitcoin/issues/3550

**Comment by ekryski** [comment]
I'm looking to see if I can fix. Making some progress locally.

**Comment by BobbyMcWho** [comment]
Looks fixed in #168 , closing

**Pull request closed without merging**
