### PR TITLE
RPC difficulty fixes

### PR DESCRIPTION
**Pull request by pallas1**
- fix GetLastBlockIndex4Algo()
- fix GetDifficulty to work on the specified algo

Also makes solo and wallet (?) mining possible.
Can be deployed without hardfork.

### CODE REVIEW

**Comment by vergecurrency** [comment]
sweet. tested this?

**Comment by pallas1** [comment]
yes of course, I've solo mined some X17 blocks with it, but since the other fix (the algo bit mask) is not applied to the network, they got rejected.
you can try it yourself: rpc calls will report the correct difficulties for all the algos (not just the one of the last block).

**Comment by vergecurrency** [comment]
excellent. i will test this and merge it today.

**Comment by vergecurrency** [comment]
perfect

**Comment by MentalCollatz** [comment]
Note that if you're relying on the getdifficulty rpc for mining then you're doing it wrong - it reports the difficulty of the last mined block, not the current difficulty (which is the case for pretty much all coins).  The only reliable way to mine is to use nBits itself.

**Comment by pallas1** [comment]
Ccminer was returning the wrong diff before the fix. But in my local tree there is also the other fix (the one on the algo mask).

**Pull request merged**
