### PR TITLE
initial support for openssl1.1

### PR DESCRIPTION
**Pull request by michpiatek**
DISCLAIMER: THIS IS NOT RELATED TO WRAITH.

Hello, I present an attempt to use openssl1.1 in Verge. This has been done mainly because of the problems with building Verge on Fedora 27

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
will test shortly. fixing bignum was on the agenda though =]

**Comment by blmalone** [comment]
why do the builds not pass on any of these PR's?

**Comment by justinvforvendetta** [comment]
@blmalone maybe you arent reading it correctly. linux is building just fine, mac and win are failing. mac is failing because of the libdb4.8 error, which is common. it builds fine on mac though. please DYOR or RTFM before making comments in the future if you dont understand what you're looking at, thanks.

**Comment by blmalone** [comment]
@justinvforvendetta didn't mean to be so blunt with my question. Thanks, I'm new to Verge code base and have been looking to make contributions where I can. I understand it probably wasn't the correct forum to ask.

**Comment by justinvforvendetta** [comment]
@blmalone you can check out the travis log and actually see where each build breaks. the builder compiles for mac, windows, and linux.

**Comment by justinvforvendetta** [comment]
@michpiatek this breaks building on any other version of openssl

**Comment by michpiatek** [comment]
@justinvforvendetta yes it does. Would you like to have a version supporting both 1.0.2 and 1.1.0?

**Pull request merged**
