### PR TITLE
Update to levelDB 1.20

### PR DESCRIPTION
**Pull request by mjanveaux**

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
this fails, i double checked. looks close though.

**Comment by jrsikors** [comment]
compile errors on Linux & Mac:

> Building LevelDB ...
> make[3]: *** No rule to make target `libmemenv.a'.  Stop.
> make[2]: *** [leveldb/libmemenv.a] Error 2
> make[1]: *** [check] Error 2
> make: *** [check-recursive] Error 1
> cat: src/test-suite.log: No such file or directory
> The command "./building/${VERGE_PLATFORM}/build.sh" failed and exited with 1 during .
> Your build has been stopped.

**Comment by jrsikors** [comment]
per serverlag on https://github.com/vergecurrency/VERGE/issues/298

> Thinking you might need to do the following:
> 
> cd src/leveldb
> chmod +x build_detect_platform
> make clean
> make libmemenv.a libleveldb.a

**Comment by jrsikors** [comment]
closing -- levelDB pull req now on #715

**Pull request closed without merging**
